version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Ubuntu1804
install:
- sh: >-
    sudo apt-get update

    sudo apt-get install texlive texlive-lang-german texlive-latex-extra biber texlive-bibtex-extra -y
build_script:
- sh: >-
    pdflatex main.tex

    biber main

    pdflatex main.tex
test: off
deploy: off